window:
  fullscreen: False

colors:
  backgroundColor: "#000000"
  green: "#43dba8"
  lightBlue: "#263755"
  mediumBlue: "#1e2a42"
  darkBlue: "#161d2d"
  pressurePlot: "#f1c40f"
  flowPlot: "#9b59b6"
  alarmColor: "#FF0749"

defaultSettings:
  start: 0
  peep: 5
  freq: 20
  ratio: 20
  ratio_step: 0.5
  pressure: 30
  oxygen: 25
  max_pressure: 50
  min_pressure: 20
  pressure_step: 5
  max_tv: 800
  min_tv: 50
  tv_step: 50
  max_fio2: 60
  min_fio2: 20
  fio2_step: 5
  max_peep: 35
  min_peep: 5
  peep_step: 5
  min_freq: 0
  max_freq: 30
  freq_step: 1

alarmSettings:
  min_pressure: 20
  max_pressure: 50
  min_peep: 5
  max_peep: 35
  min_fio2: 20
  max_fio2: 50
  min_tv: 500
  max_tv: 800

developer:
  simulate: True
  commPort: '/dev/ttyS0'
  baudrate: 500000
  logEnabled: True
  logDir: "sensorlogs"

  # for Mac
#TTY = '/dev/cu.usbmodemC1DDCDF83'
# for Ubuntu
#TTY = '/dev/ttyUSB0'