window:
  fullscreen: False

colors:
  backgroundColor: "#000000"

defaultSettings:
  start: 0
  peep: 5
  freq: 20
  ratio: 2
  pressure: 30
  oxygen: 25
  max_pressure: 50
  min_pressure: 20
  max_tv: 800
  min_tv: 50
  max_fio2: 50
  min_fio2: 20
  max_peep: 35
  min_peep: 5

developer:
  simulate: False
  commPort: '/dev/ttyS0'
  baudrate: 500000
  logEnabled: True
  logDir: "/logs"

  # for Mac
#TTY = '/dev/cu.usbmodemC1DDCDF83'
# for Ubuntu
#TTY = '/dev/ttyUSB0'